### ISSUE TITLE
Harmonization of the DATS.json date type field

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#499]
## Purpose

Harmonization of the date types values of the DATS.json files describing datasets.

Convention: date type values should be all lower case except for "CONP DATS fileset creation date" where the acronyms should be capitalized.

**Initial list of date types based on what is already present in the datasets:**
- CONP DATS JSON fileset creation date
- start date
- end date
- release date
- last update date

## Context

This is one subtask related to #454

## Possible Implementation (optional)

- [x] convert date types in the existing DATS files to comply with convention above for non-crawled datasets:
  - [x] mcgill-emc-rna-seq-experiment https://github.com/CONP-PCNO/conp-dataset/pull/497
  - [x] all 3 Khanlab datasets https://github.com/CONP-PCNO/conp-dataset/pull/492
  - [x] all 3 PREVENT-AD datasets #500
  - [x] all 3 braincode datasets #500
  - [x] multicenter-phantom 
  - [x] visual-working-memory #500
  - [x] Reusing-Neuro-Data #500
  - [x] cneuromod #502
  - [x] SIMON #500
- [ ] modify the DATS GUI editor to automatically save the date type in lower case except for 'CONP DATS fileset creation date', https://github.com/CONP-PCNO/conp-dats-editor/issues/15
- [x] modify the validator script and tests to enforce the convention #519

## Related issues 

#454
