### ISSUE TITLE
Harmonize DATS privacy field 

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#532]
**The allowed values for the privacy field should be one of the following terms:**
- open
- registered
- controlled
- private

**Proposed definitions for the 4 terms:**
- open: freely and publicly available
- registered: available to bona fide researchers/clinical care professionals only
- controlled: available to qualified researchers approved by a committee after review of their research proposal; also known as managed or restricted access
- private: available only to researchers of the project; also known as closed

**TODOs**
- [x]  add documentation about this field in [CONP DATS fields.md](https://github.com/CONP-PCNO/conp-documentation/blob/master/CONP_DATS_fields.md) - [conp-documentation/issues/59](https://github.com/CONP-PCNO/conp-documentation/issues/59)
- [x] update the validator and tests to allow only for those 4 terms in the privacy field #534 
- [x] review and correct the datasets for which the `privacy` field of the DATS file is incorrectly entered https://github.com/CONP-PCNO/conp-dataset/issues/536
- [x] check if crawlers need to be updated for this DATS field
- [x] modify the DATS GUI to allow for those 4 terms and include the definition [conp-dats-editor/issues/16](https://github.com/CONP-PCNO/conp-dats-editor/issues/16)
- [x] modify default displayed value on the portal for privacy from public to open [conp-portal/issues/414](https://github.com/CONP-PCNO/conp-portal/issues/414)
- [x] submit the terms to NIDM #535

**Comment by cmadjar** [comment]
@emmetaobrien @PapillonMcGill @zxenia could you verify that the definition I propose above make sense? Thanks!

**Comment by PapillonMcGill** [comment]
Yes, it make sense with what was discussed

**Comment by emmetaobrien** [comment]
That all looks good to me.

**Comment by cmadjar** [comment]
Crawlers do not need to be updated for this field. Yeah! One less thing to do :)

**Comment by zxenia** [comment]
The definitions look good to me too.
