### ISSUE TITLE
Harmonize DATS isAbout field

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#533]
Values in this field should refer to biological entities. Species should always be included in this field. Other values can include diseases (Alzheimer's disease) or category (older adult, healthy...). 

Values in this field should be in lower case unless it is an acronym or know to required an upper case letter.

For the taxonomy, it should be using the terms from the NCBI taxonomy browser: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi

**TODOs**
- [x] fix the wrong terminology used for the `isAbout` field in the current DATS files #537
- [ ] modify the DATS GUI so that it reads the NCBI taxonomy to hint users for species entries [conp-dats-editor/issues/17](https://github.com/CONP-PCNO/conp-dats-editor/issues/17)
- [x] submit terms other than species to NIDM #535

Note: crawlers do not need to be updated for this field since the `isAbout` field cannot be automatically populated from Zenodo and OSF responses. This does not mean that some of the crawled dataset won't need to be updated if the users uploaded a DATS.json file. In which case, will need to contact the user so they can update their dataset.

**Comment by cmadjar** [comment]
@emmetaobrien @PapillonMcGill @zxenia I am not sure to which extent we can add this field to the validator. For now, I did not mention the validator and tests in the description of this issue. Thoughts?

**Comment by emmetaobrien** [comment]
We could require that under `isAbout` there must be an `identifier` with an `identifierSource` containing a value that starts with the string `https://www.ncbi.nlm.nih.gov/Taxonomy`; it's a bit clumsy but it's as good a way as I can see of confirming that the species is specified.
