### ISSUE TITLE
Harmonize DATS licenses field

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#541]
List of terms:
- CC BY
- CC BY-SA
- CC BY-NC
- CC BY-NC-SA
- CC BY-ND
- CC BY-NC-ND
- CC0
- ODbL
- ODC-By
- PDDL

**TODOs:**
- [x] find out which default value should be used when none are specified #539
- [x] fix datasets with wrong term for the license #540
- [x] crawlers default value is None for that field currently. Figure out whether we need to change that value to a default setting or keep it as None TO BE DISCUSSED
- [x] submit terms to NIDM #535

**Comment by cmadjar** [comment]
@emmetaobrien @PapillonMcGill @zxenia if you have any ideas on how to incorporate this in the DATS validator. It might be tricky since users can enter URLs and other things in that field...

**Comment by zxenia** [comment]
@cmadjar I don't think we need to add this in the dats validator because exactly what you said - we still want to allow users to use their own licenses and terms of use. When we prepare those terms we can add them in docs [here](https://github.com/CONP-PCNO/conp-documentation/blob/master/CONP_DATS_fields.md) as suggested licenses but leave a note that the users still can add their own. And once it's in the dats editor we minimize the probability that the same license is spelled differently.
